FROM public.ecr.aws/lambda/nodejs:16-x86_64

# Copy function code
ADD dist ${LAMBDA_TASK_ROOT}
COPY runtime.mjs /var/runtime/index.mjs
COPY bootstrap /var/runtime/bootstrap

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "index.handler" ] 
# need to override with handler.<>
